// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.35.1
// source: vested/v1/connector_hub.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientDuplexStream,
  type ClientOptions,
  type handleBidiStreamingCall,
  makeGenericClientConstructor,
  type Metadata,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { Struct } from "../../google/protobuf/struct";
import { Timestamp } from "../../google/protobuf/timestamp";

export const protobufPackage = "vested.v1";

export enum ResultKind {
  /** RESULT_KIND_SINGLE - one atomic result (today's behavior) */
  RESULT_KIND_SINGLE = 0,
  /** RESULT_KIND_ROWSET - paginated row set (sample-in-context, full by-reference) */
  RESULT_KIND_ROWSET = 1,
  UNRECOGNIZED = -1,
}

export function resultKindFromJSON(object: any): ResultKind {
  switch (object) {
    case 0:
    case "RESULT_KIND_SINGLE":
      return ResultKind.RESULT_KIND_SINGLE;
    case 1:
    case "RESULT_KIND_ROWSET":
      return ResultKind.RESULT_KIND_ROWSET;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ResultKind.UNRECOGNIZED;
  }
}

export function resultKindToJSON(object: ResultKind): string {
  switch (object) {
    case ResultKind.RESULT_KIND_SINGLE:
      return "RESULT_KIND_SINGLE";
    case ResultKind.RESULT_KIND_ROWSET:
      return "RESULT_KIND_ROWSET";
    case ResultKind.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface ConnectorMsg {
  hello?: Hello | undefined;
  register?: Register | undefined;
  toolCallResponse?: ToolCallResponse | undefined;
  heartbeat?: Heartbeat | undefined;
  credentialOpResponse?: CredentialOpResponse | undefined;
}

export interface Hello {
  sdkLanguage: string;
  sdkVersion: string;
  workerId: string;
}

export interface Register {
  baselineFingerprint: string;
  agents: AgentDecl[];
  /**
   * Absent = this connector uses no per-user auth; the platform then hides it
   * from the user-facing credential UI entirely and never gates its tools.
   */
  credentialSchema: CredentialSchemaDecl | undefined;
}

/**
 * Declares that this connector's tools act on behalf of the calling user and
 * need credentials that only the worker can read. The core renders a form from
 * this declaration and seals what the user types to the connector's public key.
 */
export interface CredentialSchemaDecl {
  /** "basic" | "token" | "custom" */
  kind: string;
  /** shown as the form heading, e.g. "Al-Saif ERP account" */
  title: string;
  helpText: string;
  fields: CredentialFieldDecl[];
}

export interface CredentialFieldDecl {
  /** map key in the sealed field map, e.g. "username" */
  key: string;
  label: string;
  /** "text" | "password" | "url" | "select" */
  type: string;
  required: boolean;
  placeholder: string;
  /** "select" only */
  options: string[];
}

export interface AgentDecl {
  key: string;
  name: string;
  description: string;
  /** "active" | "inactive" */
  status: string;
  model: ModelDecl | undefined;
  instructions: InstructionDecl[];
  tools: ToolDecl[];
}

export interface ModelDecl {
  provider: string;
  name: string;
  config: { [key: string]: any } | undefined;
}

export interface InstructionDecl {
  type: string;
  format: string;
  body: string;
  position: number;
}

export interface ToolDecl {
  key: string;
  name: string;
  description: string;
  /** raw JSON Schema; bytes avoids UTF-8 validation */
  inputSchemaJson: Uint8Array;
  /** raw JSON Schema; bytes avoids UTF-8 validation */
  outputSchemaJson: Uint8Array;
  defaultDeadlineMs: number;
  maxResultBytes: number;
  /**
   * Connector-declared tool sensitivity. One of:
   * "read" | "write" | "destructive" | "external_call" | "medium".
   * Empty = unset; the hub defaults it to "external_call". Admins can
   * override the effective value later in the admin UI.
   */
  sensitivity: string;
  /** SINGLE unless the tool is a PaginatedToolHandler */
  resultKind: ResultKind;
}

export interface ToolCallResponse {
  invocationId: string;
  /** JSON-encoded; validated against tool output_schema on receive */
  resultJson?: Uint8Array | undefined;
  error?: string | undefined;
  durationMs: number;
  /** empty = last page (ROWSET only) */
  nextCursor: string;
  /** 0 = unknown (ROWSET only) */
  totalRows: number;
}

export interface Heartbeat {
  at: Date | undefined;
}

export interface HubMsg {
  helloAck?: HelloAck | undefined;
  registerAck?: RegisterAck | undefined;
  toolCallRequest?: ToolCallRequest | undefined;
  heartbeatAck?: HeartbeatAck | undefined;
  goAway?: GoAway | undefined;
  credentialOpRequest?: CredentialOpRequest | undefined;
}

/**
 * Asks the connector to do something with a user's sealed credential that only
 * it can do: try it against the real system, or tear down a remote session.
 * The core cannot open the envelope, so every credential-lifecycle question is
 * answered here or not at all.
 */
export interface CredentialOpRequest {
  opId: string;
  /** "validate" | "revoke" */
  op: string;
  userId: string;
  userEmail: string;
  employeeNo: string;
  erpIdentifier: string;
  /** the sealed envelope, verbatim */
  envelopeJson: Uint8Array;
  deadlineMs: number;
}

export interface CredentialOpResponse {
  opId: string;
  ok: boolean;
  /** User-facing. The connector must not put the credential in here. */
  error: string;
  /** Non-secret facts to show the user, e.g. {"account": "j.smith@erp"}. */
  display: { [key: string]: any } | undefined;
}

export interface HelloAck {
  connectorId: string;
  organizationId: string;
  namespace: string;
  maxAgents: number;
  maxToolsPerAgent: number;
  maxConcurrentToolCalls: number;
}

export interface RegisterAck {
  baselineFingerprint: string;
  /** "accepted" | "rejected" */
  status: string;
  issues: DeclIssue[];
}

export interface DeclIssue {
  path: string;
  code: string;
  message: string;
}

export interface ToolCallRequest {
  invocationId: string;
  agentKey: string;
  toolKey: string;
  /** JSON-encoded; validated against tool input_schema before send */
  argsJson: Uint8Array;
  organizationId: string;
  userId: string;
  conversationId: string;
  deadlineMs: number;
  userEmail: string;
  /**
   * Optional ERP/HR identity of the calling user, so a connector (e.g. an
   * ERP integration) can resolve who the tool call is on behalf of.
   * Empty when unset. employee_no + erp_identifier come from the user.
   * erp_department_identifiers holds the ERP identifier of EACH department
   * the user belongs to in the run's org (a user can be in several);
   * empty list when the user has no department or none carry an ERP id.
   */
  employeeNo: string;
  erpIdentifier: string;
  erpDepartmentIdentifiers: string[];
  /** opaque page cursor; empty = first page (ROWSET only) */
  cursor: string;
  /** requested rows/page; 0 = connector default (ROWSET only) */
  pageSize: number;
  /**
   * The calling user's sealed credential, forwarded verbatim. Present only for
   * connectors that declared a credential_schema; empty for every other
   * connector, which is what keeps existing integrations ungated. The hub
   * cannot open it — only the worker's private key can.
   */
  credentialEnvelopeJson: Uint8Array;
}

export interface HeartbeatAck {
  at: Date | undefined;
}

export interface GoAway {
  reason: string;
}

function createBaseConnectorMsg(): ConnectorMsg {
  return {};
}

export const ConnectorMsg: MessageFns<ConnectorMsg> = {
  encode(message: ConnectorMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.hello !== undefined) {
      Hello.encode(message.hello, writer.uint32(10).fork()).join();
    }
    if (message.register !== undefined) {
      Register.encode(message.register, writer.uint32(18).fork()).join();
    }
    if (message.toolCallResponse !== undefined) {
      ToolCallResponse.encode(message.toolCallResponse, writer.uint32(26).fork()).join();
    }
    if (message.heartbeat !== undefined) {
      Heartbeat.encode(message.heartbeat, writer.uint32(34).fork()).join();
    }
    if (message.credentialOpResponse !== undefined) {
      CredentialOpResponse.encode(message.credentialOpResponse, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConnectorMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConnectorMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.hello = Hello.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.register = Register.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toolCallResponse = ToolCallResponse.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.heartbeat = Heartbeat.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.credentialOpResponse = CredentialOpResponse.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConnectorMsg {
    return {
      hello: isSet(object.hello) ? Hello.fromJSON(object.hello) : undefined,
      register: isSet(object.register) ? Register.fromJSON(object.register) : undefined,
      toolCallResponse: isSet(object.toolCallResponse)
        ? ToolCallResponse.fromJSON(object.toolCallResponse)
        : isSet(object.tool_call_response)
        ? ToolCallResponse.fromJSON(object.tool_call_response)
        : undefined,
      heartbeat: isSet(object.heartbeat) ? Heartbeat.fromJSON(object.heartbeat) : undefined,
      credentialOpResponse: isSet(object.credentialOpResponse)
        ? CredentialOpResponse.fromJSON(object.credentialOpResponse)
        : isSet(object.credential_op_response)
        ? CredentialOpResponse.fromJSON(object.credential_op_response)
        : undefined,
    };
  },

  toJSON(message: ConnectorMsg): unknown {
    const obj: any = {};
    if (message.hello !== undefined) {
      obj.hello = Hello.toJSON(message.hello);
    }
    if (message.register !== undefined) {
      obj.register = Register.toJSON(message.register);
    }
    if (message.toolCallResponse !== undefined) {
      obj.toolCallResponse = ToolCallResponse.toJSON(message.toolCallResponse);
    }
    if (message.heartbeat !== undefined) {
      obj.heartbeat = Heartbeat.toJSON(message.heartbeat);
    }
    if (message.credentialOpResponse !== undefined) {
      obj.credentialOpResponse = CredentialOpResponse.toJSON(message.credentialOpResponse);
    }
    return obj;
  },

  create(base?: DeepPartial<ConnectorMsg>): ConnectorMsg {
    return ConnectorMsg.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ConnectorMsg>): ConnectorMsg {
    const message = createBaseConnectorMsg();
    message.hello = (object.hello !== undefined && object.hello !== null) ? Hello.fromPartial(object.hello) : undefined;
    message.register = (object.register !== undefined && object.register !== null)
      ? Register.fromPartial(object.register)
      : undefined;
    message.toolCallResponse = (object.toolCallResponse !== undefined && object.toolCallResponse !== null)
      ? ToolCallResponse.fromPartial(object.toolCallResponse)
      : undefined;
    message.heartbeat = (object.heartbeat !== undefined && object.heartbeat !== null)
      ? Heartbeat.fromPartial(object.heartbeat)
      : undefined;
    message.credentialOpResponse = (object.credentialOpResponse !== undefined && object.credentialOpResponse !== null)
      ? CredentialOpResponse.fromPartial(object.credentialOpResponse)
      : undefined;
    return message;
  },
};

function createBaseHello(): Hello {
  return { sdkLanguage: "", sdkVersion: "", workerId: "" };
}

export const Hello: MessageFns<Hello> = {
  encode(message: Hello, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sdkLanguage !== "") {
      writer.uint32(10).string(message.sdkLanguage);
    }
    if (message.sdkVersion !== "") {
      writer.uint32(18).string(message.sdkVersion);
    }
    if (message.workerId !== "") {
      writer.uint32(26).string(message.workerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Hello {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHello();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sdkLanguage = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.sdkVersion = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.workerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Hello {
    return {
      sdkLanguage: isSet(object.sdkLanguage)
        ? globalThis.String(object.sdkLanguage)
        : isSet(object.sdk_language)
        ? globalThis.String(object.sdk_language)
        : "",
      sdkVersion: isSet(object.sdkVersion)
        ? globalThis.String(object.sdkVersion)
        : isSet(object.sdk_version)
        ? globalThis.String(object.sdk_version)
        : "",
      workerId: isSet(object.workerId)
        ? globalThis.String(object.workerId)
        : isSet(object.worker_id)
        ? globalThis.String(object.worker_id)
        : "",
    };
  },

  toJSON(message: Hello): unknown {
    const obj: any = {};
    if (message.sdkLanguage !== "") {
      obj.sdkLanguage = message.sdkLanguage;
    }
    if (message.sdkVersion !== "") {
      obj.sdkVersion = message.sdkVersion;
    }
    if (message.workerId !== "") {
      obj.workerId = message.workerId;
    }
    return obj;
  },

  create(base?: DeepPartial<Hello>): Hello {
    return Hello.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Hello>): Hello {
    const message = createBaseHello();
    message.sdkLanguage = object.sdkLanguage ?? "";
    message.sdkVersion = object.sdkVersion ?? "";
    message.workerId = object.workerId ?? "";
    return message;
  },
};

function createBaseRegister(): Register {
  return { baselineFingerprint: "", agents: [], credentialSchema: undefined };
}

export const Register: MessageFns<Register> = {
  encode(message: Register, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baselineFingerprint !== "") {
      writer.uint32(10).string(message.baselineFingerprint);
    }
    for (const v of message.agents) {
      AgentDecl.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.credentialSchema !== undefined) {
      CredentialSchemaDecl.encode(message.credentialSchema, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Register {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegister();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baselineFingerprint = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agents.push(AgentDecl.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.credentialSchema = CredentialSchemaDecl.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Register {
    return {
      baselineFingerprint: isSet(object.baselineFingerprint)
        ? globalThis.String(object.baselineFingerprint)
        : isSet(object.baseline_fingerprint)
        ? globalThis.String(object.baseline_fingerprint)
        : "",
      agents: globalThis.Array.isArray(object?.agents) ? object.agents.map((e: any) => AgentDecl.fromJSON(e)) : [],
      credentialSchema: isSet(object.credentialSchema)
        ? CredentialSchemaDecl.fromJSON(object.credentialSchema)
        : isSet(object.credential_schema)
        ? CredentialSchemaDecl.fromJSON(object.credential_schema)
        : undefined,
    };
  },

  toJSON(message: Register): unknown {
    const obj: any = {};
    if (message.baselineFingerprint !== "") {
      obj.baselineFingerprint = message.baselineFingerprint;
    }
    if (message.agents?.length) {
      obj.agents = message.agents.map((e) => AgentDecl.toJSON(e));
    }
    if (message.credentialSchema !== undefined) {
      obj.credentialSchema = CredentialSchemaDecl.toJSON(message.credentialSchema);
    }
    return obj;
  },

  create(base?: DeepPartial<Register>): Register {
    return Register.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Register>): Register {
    const message = createBaseRegister();
    message.baselineFingerprint = object.baselineFingerprint ?? "";
    message.agents = object.agents?.map((e) => AgentDecl.fromPartial(e)) || [];
    message.credentialSchema = (object.credentialSchema !== undefined && object.credentialSchema !== null)
      ? CredentialSchemaDecl.fromPartial(object.credentialSchema)
      : undefined;
    return message;
  },
};

function createBaseCredentialSchemaDecl(): CredentialSchemaDecl {
  return { kind: "", title: "", helpText: "", fields: [] };
}

export const CredentialSchemaDecl: MessageFns<CredentialSchemaDecl> = {
  encode(message: CredentialSchemaDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.kind !== "") {
      writer.uint32(10).string(message.kind);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.helpText !== "") {
      writer.uint32(26).string(message.helpText);
    }
    for (const v of message.fields) {
      CredentialFieldDecl.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialSchemaDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialSchemaDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.helpText = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fields.push(CredentialFieldDecl.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialSchemaDecl {
    return {
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      helpText: isSet(object.helpText)
        ? globalThis.String(object.helpText)
        : isSet(object.help_text)
        ? globalThis.String(object.help_text)
        : "",
      fields: globalThis.Array.isArray(object?.fields)
        ? object.fields.map((e: any) => CredentialFieldDecl.fromJSON(e))
        : [],
    };
  },

  toJSON(message: CredentialSchemaDecl): unknown {
    const obj: any = {};
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.helpText !== "") {
      obj.helpText = message.helpText;
    }
    if (message.fields?.length) {
      obj.fields = message.fields.map((e) => CredentialFieldDecl.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<CredentialSchemaDecl>): CredentialSchemaDecl {
    return CredentialSchemaDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CredentialSchemaDecl>): CredentialSchemaDecl {
    const message = createBaseCredentialSchemaDecl();
    message.kind = object.kind ?? "";
    message.title = object.title ?? "";
    message.helpText = object.helpText ?? "";
    message.fields = object.fields?.map((e) => CredentialFieldDecl.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCredentialFieldDecl(): CredentialFieldDecl {
  return { key: "", label: "", type: "", required: false, placeholder: "", options: [] };
}

export const CredentialFieldDecl: MessageFns<CredentialFieldDecl> = {
  encode(message: CredentialFieldDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.label !== "") {
      writer.uint32(18).string(message.label);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.required !== false) {
      writer.uint32(32).bool(message.required);
    }
    if (message.placeholder !== "") {
      writer.uint32(42).string(message.placeholder);
    }
    for (const v of message.options) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialFieldDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialFieldDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.label = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.required = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.placeholder = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.options.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialFieldDecl {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      label: isSet(object.label) ? globalThis.String(object.label) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      required: isSet(object.required) ? globalThis.Boolean(object.required) : false,
      placeholder: isSet(object.placeholder) ? globalThis.String(object.placeholder) : "",
      options: globalThis.Array.isArray(object?.options) ? object.options.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: CredentialFieldDecl): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.label !== "") {
      obj.label = message.label;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.required !== false) {
      obj.required = message.required;
    }
    if (message.placeholder !== "") {
      obj.placeholder = message.placeholder;
    }
    if (message.options?.length) {
      obj.options = message.options;
    }
    return obj;
  },

  create(base?: DeepPartial<CredentialFieldDecl>): CredentialFieldDecl {
    return CredentialFieldDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CredentialFieldDecl>): CredentialFieldDecl {
    const message = createBaseCredentialFieldDecl();
    message.key = object.key ?? "";
    message.label = object.label ?? "";
    message.type = object.type ?? "";
    message.required = object.required ?? false;
    message.placeholder = object.placeholder ?? "";
    message.options = object.options?.map((e) => e) || [];
    return message;
  },
};

function createBaseAgentDecl(): AgentDecl {
  return { key: "", name: "", description: "", status: "", model: undefined, instructions: [], tools: [] };
}

export const AgentDecl: MessageFns<AgentDecl> = {
  encode(message: AgentDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.status !== "") {
      writer.uint32(34).string(message.status);
    }
    if (message.model !== undefined) {
      ModelDecl.encode(message.model, writer.uint32(42).fork()).join();
    }
    for (const v of message.instructions) {
      InstructionDecl.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.tools) {
      ToolDecl.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AgentDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAgentDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.model = ModelDecl.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.instructions.push(InstructionDecl.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.tools.push(ToolDecl.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AgentDecl {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      model: isSet(object.model) ? ModelDecl.fromJSON(object.model) : undefined,
      instructions: globalThis.Array.isArray(object?.instructions)
        ? object.instructions.map((e: any) => InstructionDecl.fromJSON(e))
        : [],
      tools: globalThis.Array.isArray(object?.tools) ? object.tools.map((e: any) => ToolDecl.fromJSON(e)) : [],
    };
  },

  toJSON(message: AgentDecl): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.model !== undefined) {
      obj.model = ModelDecl.toJSON(message.model);
    }
    if (message.instructions?.length) {
      obj.instructions = message.instructions.map((e) => InstructionDecl.toJSON(e));
    }
    if (message.tools?.length) {
      obj.tools = message.tools.map((e) => ToolDecl.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<AgentDecl>): AgentDecl {
    return AgentDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AgentDecl>): AgentDecl {
    const message = createBaseAgentDecl();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.status = object.status ?? "";
    message.model = (object.model !== undefined && object.model !== null)
      ? ModelDecl.fromPartial(object.model)
      : undefined;
    message.instructions = object.instructions?.map((e) => InstructionDecl.fromPartial(e)) || [];
    message.tools = object.tools?.map((e) => ToolDecl.fromPartial(e)) || [];
    return message;
  },
};

function createBaseModelDecl(): ModelDecl {
  return { provider: "", name: "", config: undefined };
}

export const ModelDecl: MessageFns<ModelDecl> = {
  encode(message: ModelDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.provider !== "") {
      writer.uint32(10).string(message.provider);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.config !== undefined) {
      Struct.encode(Struct.wrap(message.config), writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ModelDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseModelDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.config = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ModelDecl {
    return {
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      config: isObject(object.config) ? object.config : undefined,
    };
  },

  toJSON(message: ModelDecl): unknown {
    const obj: any = {};
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.config !== undefined) {
      obj.config = message.config;
    }
    return obj;
  },

  create(base?: DeepPartial<ModelDecl>): ModelDecl {
    return ModelDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ModelDecl>): ModelDecl {
    const message = createBaseModelDecl();
    message.provider = object.provider ?? "";
    message.name = object.name ?? "";
    message.config = object.config ?? undefined;
    return message;
  },
};

function createBaseInstructionDecl(): InstructionDecl {
  return { type: "", format: "", body: "", position: 0 };
}

export const InstructionDecl: MessageFns<InstructionDecl> = {
  encode(message: InstructionDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.format !== "") {
      writer.uint32(18).string(message.format);
    }
    if (message.body !== "") {
      writer.uint32(26).string(message.body);
    }
    if (message.position !== 0) {
      writer.uint32(32).uint32(message.position);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): InstructionDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInstructionDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.format = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.body = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.position = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InstructionDecl {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      format: isSet(object.format) ? globalThis.String(object.format) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
      position: isSet(object.position) ? globalThis.Number(object.position) : 0,
    };
  },

  toJSON(message: InstructionDecl): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.format !== "") {
      obj.format = message.format;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    if (message.position !== 0) {
      obj.position = Math.round(message.position);
    }
    return obj;
  },

  create(base?: DeepPartial<InstructionDecl>): InstructionDecl {
    return InstructionDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<InstructionDecl>): InstructionDecl {
    const message = createBaseInstructionDecl();
    message.type = object.type ?? "";
    message.format = object.format ?? "";
    message.body = object.body ?? "";
    message.position = object.position ?? 0;
    return message;
  },
};

function createBaseToolDecl(): ToolDecl {
  return {
    key: "",
    name: "",
    description: "",
    inputSchemaJson: new Uint8Array(0),
    outputSchemaJson: new Uint8Array(0),
    defaultDeadlineMs: 0,
    maxResultBytes: 0,
    sensitivity: "",
    resultKind: 0,
  };
}

export const ToolDecl: MessageFns<ToolDecl> = {
  encode(message: ToolDecl, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== "") {
      writer.uint32(10).string(message.key);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.description !== "") {
      writer.uint32(26).string(message.description);
    }
    if (message.inputSchemaJson.length !== 0) {
      writer.uint32(34).bytes(message.inputSchemaJson);
    }
    if (message.outputSchemaJson.length !== 0) {
      writer.uint32(42).bytes(message.outputSchemaJson);
    }
    if (message.defaultDeadlineMs !== 0) {
      writer.uint32(48).uint32(message.defaultDeadlineMs);
    }
    if (message.maxResultBytes !== 0) {
      writer.uint32(56).uint32(message.maxResultBytes);
    }
    if (message.sensitivity !== "") {
      writer.uint32(66).string(message.sensitivity);
    }
    if (message.resultKind !== 0) {
      writer.uint32(72).int32(message.resultKind);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolDecl {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolDecl();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.key = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.inputSchemaJson = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.outputSchemaJson = reader.bytes();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.defaultDeadlineMs = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.maxResultBytes = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.sensitivity = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.resultKind = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolDecl {
    return {
      key: isSet(object.key) ? globalThis.String(object.key) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      inputSchemaJson: isSet(object.inputSchemaJson)
        ? bytesFromBase64(object.inputSchemaJson)
        : isSet(object.input_schema_json)
        ? bytesFromBase64(object.input_schema_json)
        : new Uint8Array(0),
      outputSchemaJson: isSet(object.outputSchemaJson)
        ? bytesFromBase64(object.outputSchemaJson)
        : isSet(object.output_schema_json)
        ? bytesFromBase64(object.output_schema_json)
        : new Uint8Array(0),
      defaultDeadlineMs: isSet(object.defaultDeadlineMs)
        ? globalThis.Number(object.defaultDeadlineMs)
        : isSet(object.default_deadline_ms)
        ? globalThis.Number(object.default_deadline_ms)
        : 0,
      maxResultBytes: isSet(object.maxResultBytes)
        ? globalThis.Number(object.maxResultBytes)
        : isSet(object.max_result_bytes)
        ? globalThis.Number(object.max_result_bytes)
        : 0,
      sensitivity: isSet(object.sensitivity) ? globalThis.String(object.sensitivity) : "",
      resultKind: isSet(object.resultKind)
        ? resultKindFromJSON(object.resultKind)
        : isSet(object.result_kind)
        ? resultKindFromJSON(object.result_kind)
        : 0,
    };
  },

  toJSON(message: ToolDecl): unknown {
    const obj: any = {};
    if (message.key !== "") {
      obj.key = message.key;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.inputSchemaJson.length !== 0) {
      obj.inputSchemaJson = base64FromBytes(message.inputSchemaJson);
    }
    if (message.outputSchemaJson.length !== 0) {
      obj.outputSchemaJson = base64FromBytes(message.outputSchemaJson);
    }
    if (message.defaultDeadlineMs !== 0) {
      obj.defaultDeadlineMs = Math.round(message.defaultDeadlineMs);
    }
    if (message.maxResultBytes !== 0) {
      obj.maxResultBytes = Math.round(message.maxResultBytes);
    }
    if (message.sensitivity !== "") {
      obj.sensitivity = message.sensitivity;
    }
    if (message.resultKind !== 0) {
      obj.resultKind = resultKindToJSON(message.resultKind);
    }
    return obj;
  },

  create(base?: DeepPartial<ToolDecl>): ToolDecl {
    return ToolDecl.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ToolDecl>): ToolDecl {
    const message = createBaseToolDecl();
    message.key = object.key ?? "";
    message.name = object.name ?? "";
    message.description = object.description ?? "";
    message.inputSchemaJson = object.inputSchemaJson ?? new Uint8Array(0);
    message.outputSchemaJson = object.outputSchemaJson ?? new Uint8Array(0);
    message.defaultDeadlineMs = object.defaultDeadlineMs ?? 0;
    message.maxResultBytes = object.maxResultBytes ?? 0;
    message.sensitivity = object.sensitivity ?? "";
    message.resultKind = object.resultKind ?? 0;
    return message;
  },
};

function createBaseToolCallResponse(): ToolCallResponse {
  return { invocationId: "", durationMs: 0, nextCursor: "", totalRows: 0 };
}

export const ToolCallResponse: MessageFns<ToolCallResponse> = {
  encode(message: ToolCallResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invocationId !== "") {
      writer.uint32(10).string(message.invocationId);
    }
    if (message.resultJson !== undefined) {
      writer.uint32(18).bytes(message.resultJson);
    }
    if (message.error !== undefined) {
      writer.uint32(26).string(message.error);
    }
    if (message.durationMs !== 0) {
      writer.uint32(32).uint32(message.durationMs);
    }
    if (message.nextCursor !== "") {
      writer.uint32(42).string(message.nextCursor);
    }
    if (message.totalRows !== 0) {
      writer.uint32(48).uint64(message.totalRows);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invocationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.resultJson = reader.bytes();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.durationMs = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.nextCursor = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.totalRows = longToNumber(reader.uint64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallResponse {
    return {
      invocationId: isSet(object.invocationId)
        ? globalThis.String(object.invocationId)
        : isSet(object.invocation_id)
        ? globalThis.String(object.invocation_id)
        : "",
      resultJson: isSet(object.resultJson)
        ? bytesFromBase64(object.resultJson)
        : isSet(object.result_json)
        ? bytesFromBase64(object.result_json)
        : undefined,
      error: isSet(object.error) ? globalThis.String(object.error) : undefined,
      durationMs: isSet(object.durationMs)
        ? globalThis.Number(object.durationMs)
        : isSet(object.duration_ms)
        ? globalThis.Number(object.duration_ms)
        : 0,
      nextCursor: isSet(object.nextCursor)
        ? globalThis.String(object.nextCursor)
        : isSet(object.next_cursor)
        ? globalThis.String(object.next_cursor)
        : "",
      totalRows: isSet(object.totalRows)
        ? globalThis.Number(object.totalRows)
        : isSet(object.total_rows)
        ? globalThis.Number(object.total_rows)
        : 0,
    };
  },

  toJSON(message: ToolCallResponse): unknown {
    const obj: any = {};
    if (message.invocationId !== "") {
      obj.invocationId = message.invocationId;
    }
    if (message.resultJson !== undefined) {
      obj.resultJson = base64FromBytes(message.resultJson);
    }
    if (message.error !== undefined) {
      obj.error = message.error;
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    if (message.nextCursor !== "") {
      obj.nextCursor = message.nextCursor;
    }
    if (message.totalRows !== 0) {
      obj.totalRows = Math.round(message.totalRows);
    }
    return obj;
  },

  create(base?: DeepPartial<ToolCallResponse>): ToolCallResponse {
    return ToolCallResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ToolCallResponse>): ToolCallResponse {
    const message = createBaseToolCallResponse();
    message.invocationId = object.invocationId ?? "";
    message.resultJson = object.resultJson ?? undefined;
    message.error = object.error ?? undefined;
    message.durationMs = object.durationMs ?? 0;
    message.nextCursor = object.nextCursor ?? "";
    message.totalRows = object.totalRows ?? 0;
    return message;
  },
};

function createBaseHeartbeat(): Heartbeat {
  return { at: undefined };
}

export const Heartbeat: MessageFns<Heartbeat> = {
  encode(message: Heartbeat, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.at !== undefined) {
      Timestamp.encode(toTimestamp(message.at), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Heartbeat {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeat();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Heartbeat {
    return { at: isSet(object.at) ? fromJsonTimestamp(object.at) : undefined };
  },

  toJSON(message: Heartbeat): unknown {
    const obj: any = {};
    if (message.at !== undefined) {
      obj.at = message.at.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<Heartbeat>): Heartbeat {
    return Heartbeat.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Heartbeat>): Heartbeat {
    const message = createBaseHeartbeat();
    message.at = object.at ?? undefined;
    return message;
  },
};

function createBaseHubMsg(): HubMsg {
  return {};
}

export const HubMsg: MessageFns<HubMsg> = {
  encode(message: HubMsg, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.helloAck !== undefined) {
      HelloAck.encode(message.helloAck, writer.uint32(10).fork()).join();
    }
    if (message.registerAck !== undefined) {
      RegisterAck.encode(message.registerAck, writer.uint32(18).fork()).join();
    }
    if (message.toolCallRequest !== undefined) {
      ToolCallRequest.encode(message.toolCallRequest, writer.uint32(26).fork()).join();
    }
    if (message.heartbeatAck !== undefined) {
      HeartbeatAck.encode(message.heartbeatAck, writer.uint32(34).fork()).join();
    }
    if (message.goAway !== undefined) {
      GoAway.encode(message.goAway, writer.uint32(42).fork()).join();
    }
    if (message.credentialOpRequest !== undefined) {
      CredentialOpRequest.encode(message.credentialOpRequest, writer.uint32(50).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HubMsg {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHubMsg();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.helloAck = HelloAck.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.registerAck = RegisterAck.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toolCallRequest = ToolCallRequest.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.heartbeatAck = HeartbeatAck.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.goAway = GoAway.decode(reader, reader.uint32());
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.credentialOpRequest = CredentialOpRequest.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HubMsg {
    return {
      helloAck: isSet(object.helloAck)
        ? HelloAck.fromJSON(object.helloAck)
        : isSet(object.hello_ack)
        ? HelloAck.fromJSON(object.hello_ack)
        : undefined,
      registerAck: isSet(object.registerAck)
        ? RegisterAck.fromJSON(object.registerAck)
        : isSet(object.register_ack)
        ? RegisterAck.fromJSON(object.register_ack)
        : undefined,
      toolCallRequest: isSet(object.toolCallRequest)
        ? ToolCallRequest.fromJSON(object.toolCallRequest)
        : isSet(object.tool_call_request)
        ? ToolCallRequest.fromJSON(object.tool_call_request)
        : undefined,
      heartbeatAck: isSet(object.heartbeatAck)
        ? HeartbeatAck.fromJSON(object.heartbeatAck)
        : isSet(object.heartbeat_ack)
        ? HeartbeatAck.fromJSON(object.heartbeat_ack)
        : undefined,
      goAway: isSet(object.goAway)
        ? GoAway.fromJSON(object.goAway)
        : isSet(object.go_away)
        ? GoAway.fromJSON(object.go_away)
        : undefined,
      credentialOpRequest: isSet(object.credentialOpRequest)
        ? CredentialOpRequest.fromJSON(object.credentialOpRequest)
        : isSet(object.credential_op_request)
        ? CredentialOpRequest.fromJSON(object.credential_op_request)
        : undefined,
    };
  },

  toJSON(message: HubMsg): unknown {
    const obj: any = {};
    if (message.helloAck !== undefined) {
      obj.helloAck = HelloAck.toJSON(message.helloAck);
    }
    if (message.registerAck !== undefined) {
      obj.registerAck = RegisterAck.toJSON(message.registerAck);
    }
    if (message.toolCallRequest !== undefined) {
      obj.toolCallRequest = ToolCallRequest.toJSON(message.toolCallRequest);
    }
    if (message.heartbeatAck !== undefined) {
      obj.heartbeatAck = HeartbeatAck.toJSON(message.heartbeatAck);
    }
    if (message.goAway !== undefined) {
      obj.goAway = GoAway.toJSON(message.goAway);
    }
    if (message.credentialOpRequest !== undefined) {
      obj.credentialOpRequest = CredentialOpRequest.toJSON(message.credentialOpRequest);
    }
    return obj;
  },

  create(base?: DeepPartial<HubMsg>): HubMsg {
    return HubMsg.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HubMsg>): HubMsg {
    const message = createBaseHubMsg();
    message.helloAck = (object.helloAck !== undefined && object.helloAck !== null)
      ? HelloAck.fromPartial(object.helloAck)
      : undefined;
    message.registerAck = (object.registerAck !== undefined && object.registerAck !== null)
      ? RegisterAck.fromPartial(object.registerAck)
      : undefined;
    message.toolCallRequest = (object.toolCallRequest !== undefined && object.toolCallRequest !== null)
      ? ToolCallRequest.fromPartial(object.toolCallRequest)
      : undefined;
    message.heartbeatAck = (object.heartbeatAck !== undefined && object.heartbeatAck !== null)
      ? HeartbeatAck.fromPartial(object.heartbeatAck)
      : undefined;
    message.goAway = (object.goAway !== undefined && object.goAway !== null)
      ? GoAway.fromPartial(object.goAway)
      : undefined;
    message.credentialOpRequest = (object.credentialOpRequest !== undefined && object.credentialOpRequest !== null)
      ? CredentialOpRequest.fromPartial(object.credentialOpRequest)
      : undefined;
    return message;
  },
};

function createBaseCredentialOpRequest(): CredentialOpRequest {
  return {
    opId: "",
    op: "",
    userId: "",
    userEmail: "",
    employeeNo: "",
    erpIdentifier: "",
    envelopeJson: new Uint8Array(0),
    deadlineMs: 0,
  };
}

export const CredentialOpRequest: MessageFns<CredentialOpRequest> = {
  encode(message: CredentialOpRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.opId !== "") {
      writer.uint32(10).string(message.opId);
    }
    if (message.op !== "") {
      writer.uint32(18).string(message.op);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.userEmail !== "") {
      writer.uint32(34).string(message.userEmail);
    }
    if (message.employeeNo !== "") {
      writer.uint32(42).string(message.employeeNo);
    }
    if (message.erpIdentifier !== "") {
      writer.uint32(50).string(message.erpIdentifier);
    }
    if (message.envelopeJson.length !== 0) {
      writer.uint32(58).bytes(message.envelopeJson);
    }
    if (message.deadlineMs !== 0) {
      writer.uint32(64).uint32(message.deadlineMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialOpRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialOpRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.opId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.op = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.employeeNo = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.erpIdentifier = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.envelopeJson = reader.bytes();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.deadlineMs = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialOpRequest {
    return {
      opId: isSet(object.opId)
        ? globalThis.String(object.opId)
        : isSet(object.op_id)
        ? globalThis.String(object.op_id)
        : "",
      op: isSet(object.op) ? globalThis.String(object.op) : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      userEmail: isSet(object.userEmail)
        ? globalThis.String(object.userEmail)
        : isSet(object.user_email)
        ? globalThis.String(object.user_email)
        : "",
      employeeNo: isSet(object.employeeNo)
        ? globalThis.String(object.employeeNo)
        : isSet(object.employee_no)
        ? globalThis.String(object.employee_no)
        : "",
      erpIdentifier: isSet(object.erpIdentifier)
        ? globalThis.String(object.erpIdentifier)
        : isSet(object.erp_identifier)
        ? globalThis.String(object.erp_identifier)
        : "",
      envelopeJson: isSet(object.envelopeJson)
        ? bytesFromBase64(object.envelopeJson)
        : isSet(object.envelope_json)
        ? bytesFromBase64(object.envelope_json)
        : new Uint8Array(0),
      deadlineMs: isSet(object.deadlineMs)
        ? globalThis.Number(object.deadlineMs)
        : isSet(object.deadline_ms)
        ? globalThis.Number(object.deadline_ms)
        : 0,
    };
  },

  toJSON(message: CredentialOpRequest): unknown {
    const obj: any = {};
    if (message.opId !== "") {
      obj.opId = message.opId;
    }
    if (message.op !== "") {
      obj.op = message.op;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.userEmail !== "") {
      obj.userEmail = message.userEmail;
    }
    if (message.employeeNo !== "") {
      obj.employeeNo = message.employeeNo;
    }
    if (message.erpIdentifier !== "") {
      obj.erpIdentifier = message.erpIdentifier;
    }
    if (message.envelopeJson.length !== 0) {
      obj.envelopeJson = base64FromBytes(message.envelopeJson);
    }
    if (message.deadlineMs !== 0) {
      obj.deadlineMs = Math.round(message.deadlineMs);
    }
    return obj;
  },

  create(base?: DeepPartial<CredentialOpRequest>): CredentialOpRequest {
    return CredentialOpRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CredentialOpRequest>): CredentialOpRequest {
    const message = createBaseCredentialOpRequest();
    message.opId = object.opId ?? "";
    message.op = object.op ?? "";
    message.userId = object.userId ?? "";
    message.userEmail = object.userEmail ?? "";
    message.employeeNo = object.employeeNo ?? "";
    message.erpIdentifier = object.erpIdentifier ?? "";
    message.envelopeJson = object.envelopeJson ?? new Uint8Array(0);
    message.deadlineMs = object.deadlineMs ?? 0;
    return message;
  },
};

function createBaseCredentialOpResponse(): CredentialOpResponse {
  return { opId: "", ok: false, error: "", display: undefined };
}

export const CredentialOpResponse: MessageFns<CredentialOpResponse> = {
  encode(message: CredentialOpResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.opId !== "") {
      writer.uint32(10).string(message.opId);
    }
    if (message.ok !== false) {
      writer.uint32(16).bool(message.ok);
    }
    if (message.error !== "") {
      writer.uint32(26).string(message.error);
    }
    if (message.display !== undefined) {
      Struct.encode(Struct.wrap(message.display), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CredentialOpResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCredentialOpResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.opId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.ok = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.error = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.display = Struct.unwrap(Struct.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CredentialOpResponse {
    return {
      opId: isSet(object.opId)
        ? globalThis.String(object.opId)
        : isSet(object.op_id)
        ? globalThis.String(object.op_id)
        : "",
      ok: isSet(object.ok) ? globalThis.Boolean(object.ok) : false,
      error: isSet(object.error) ? globalThis.String(object.error) : "",
      display: isObject(object.display) ? object.display : undefined,
    };
  },

  toJSON(message: CredentialOpResponse): unknown {
    const obj: any = {};
    if (message.opId !== "") {
      obj.opId = message.opId;
    }
    if (message.ok !== false) {
      obj.ok = message.ok;
    }
    if (message.error !== "") {
      obj.error = message.error;
    }
    if (message.display !== undefined) {
      obj.display = message.display;
    }
    return obj;
  },

  create(base?: DeepPartial<CredentialOpResponse>): CredentialOpResponse {
    return CredentialOpResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<CredentialOpResponse>): CredentialOpResponse {
    const message = createBaseCredentialOpResponse();
    message.opId = object.opId ?? "";
    message.ok = object.ok ?? false;
    message.error = object.error ?? "";
    message.display = object.display ?? undefined;
    return message;
  },
};

function createBaseHelloAck(): HelloAck {
  return {
    connectorId: "",
    organizationId: "",
    namespace: "",
    maxAgents: 0,
    maxToolsPerAgent: 0,
    maxConcurrentToolCalls: 0,
  };
}

export const HelloAck: MessageFns<HelloAck> = {
  encode(message: HelloAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.connectorId !== "") {
      writer.uint32(10).string(message.connectorId);
    }
    if (message.organizationId !== "") {
      writer.uint32(18).string(message.organizationId);
    }
    if (message.namespace !== "") {
      writer.uint32(26).string(message.namespace);
    }
    if (message.maxAgents !== 0) {
      writer.uint32(32).uint32(message.maxAgents);
    }
    if (message.maxToolsPerAgent !== 0) {
      writer.uint32(40).uint32(message.maxToolsPerAgent);
    }
    if (message.maxConcurrentToolCalls !== 0) {
      writer.uint32(48).uint32(message.maxConcurrentToolCalls);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HelloAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHelloAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.connectorId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.namespace = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.maxAgents = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.maxToolsPerAgent = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.maxConcurrentToolCalls = reader.uint32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HelloAck {
    return {
      connectorId: isSet(object.connectorId)
        ? globalThis.String(object.connectorId)
        : isSet(object.connector_id)
        ? globalThis.String(object.connector_id)
        : "",
      organizationId: isSet(object.organizationId)
        ? globalThis.String(object.organizationId)
        : isSet(object.organization_id)
        ? globalThis.String(object.organization_id)
        : "",
      namespace: isSet(object.namespace) ? globalThis.String(object.namespace) : "",
      maxAgents: isSet(object.maxAgents)
        ? globalThis.Number(object.maxAgents)
        : isSet(object.max_agents)
        ? globalThis.Number(object.max_agents)
        : 0,
      maxToolsPerAgent: isSet(object.maxToolsPerAgent)
        ? globalThis.Number(object.maxToolsPerAgent)
        : isSet(object.max_tools_per_agent)
        ? globalThis.Number(object.max_tools_per_agent)
        : 0,
      maxConcurrentToolCalls: isSet(object.maxConcurrentToolCalls)
        ? globalThis.Number(object.maxConcurrentToolCalls)
        : isSet(object.max_concurrent_tool_calls)
        ? globalThis.Number(object.max_concurrent_tool_calls)
        : 0,
    };
  },

  toJSON(message: HelloAck): unknown {
    const obj: any = {};
    if (message.connectorId !== "") {
      obj.connectorId = message.connectorId;
    }
    if (message.organizationId !== "") {
      obj.organizationId = message.organizationId;
    }
    if (message.namespace !== "") {
      obj.namespace = message.namespace;
    }
    if (message.maxAgents !== 0) {
      obj.maxAgents = Math.round(message.maxAgents);
    }
    if (message.maxToolsPerAgent !== 0) {
      obj.maxToolsPerAgent = Math.round(message.maxToolsPerAgent);
    }
    if (message.maxConcurrentToolCalls !== 0) {
      obj.maxConcurrentToolCalls = Math.round(message.maxConcurrentToolCalls);
    }
    return obj;
  },

  create(base?: DeepPartial<HelloAck>): HelloAck {
    return HelloAck.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HelloAck>): HelloAck {
    const message = createBaseHelloAck();
    message.connectorId = object.connectorId ?? "";
    message.organizationId = object.organizationId ?? "";
    message.namespace = object.namespace ?? "";
    message.maxAgents = object.maxAgents ?? 0;
    message.maxToolsPerAgent = object.maxToolsPerAgent ?? 0;
    message.maxConcurrentToolCalls = object.maxConcurrentToolCalls ?? 0;
    return message;
  },
};

function createBaseRegisterAck(): RegisterAck {
  return { baselineFingerprint: "", status: "", issues: [] };
}

export const RegisterAck: MessageFns<RegisterAck> = {
  encode(message: RegisterAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.baselineFingerprint !== "") {
      writer.uint32(10).string(message.baselineFingerprint);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    for (const v of message.issues) {
      DeclIssue.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.baselineFingerprint = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.issues.push(DeclIssue.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterAck {
    return {
      baselineFingerprint: isSet(object.baselineFingerprint)
        ? globalThis.String(object.baselineFingerprint)
        : isSet(object.baseline_fingerprint)
        ? globalThis.String(object.baseline_fingerprint)
        : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      issues: globalThis.Array.isArray(object?.issues) ? object.issues.map((e: any) => DeclIssue.fromJSON(e)) : [],
    };
  },

  toJSON(message: RegisterAck): unknown {
    const obj: any = {};
    if (message.baselineFingerprint !== "") {
      obj.baselineFingerprint = message.baselineFingerprint;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.issues?.length) {
      obj.issues = message.issues.map((e) => DeclIssue.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterAck>): RegisterAck {
    return RegisterAck.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterAck>): RegisterAck {
    const message = createBaseRegisterAck();
    message.baselineFingerprint = object.baselineFingerprint ?? "";
    message.status = object.status ?? "";
    message.issues = object.issues?.map((e) => DeclIssue.fromPartial(e)) || [];
    return message;
  },
};

function createBaseDeclIssue(): DeclIssue {
  return { path: "", code: "", message: "" };
}

export const DeclIssue: MessageFns<DeclIssue> = {
  encode(message: DeclIssue, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.path !== "") {
      writer.uint32(10).string(message.path);
    }
    if (message.code !== "") {
      writer.uint32(18).string(message.code);
    }
    if (message.message !== "") {
      writer.uint32(26).string(message.message);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeclIssue {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeclIssue();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.path = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.code = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.message = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeclIssue {
    return {
      path: isSet(object.path) ? globalThis.String(object.path) : "",
      code: isSet(object.code) ? globalThis.String(object.code) : "",
      message: isSet(object.message) ? globalThis.String(object.message) : "",
    };
  },

  toJSON(message: DeclIssue): unknown {
    const obj: any = {};
    if (message.path !== "") {
      obj.path = message.path;
    }
    if (message.code !== "") {
      obj.code = message.code;
    }
    if (message.message !== "") {
      obj.message = message.message;
    }
    return obj;
  },

  create(base?: DeepPartial<DeclIssue>): DeclIssue {
    return DeclIssue.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeclIssue>): DeclIssue {
    const message = createBaseDeclIssue();
    message.path = object.path ?? "";
    message.code = object.code ?? "";
    message.message = object.message ?? "";
    return message;
  },
};

function createBaseToolCallRequest(): ToolCallRequest {
  return {
    invocationId: "",
    agentKey: "",
    toolKey: "",
    argsJson: new Uint8Array(0),
    organizationId: "",
    userId: "",
    conversationId: "",
    deadlineMs: 0,
    userEmail: "",
    employeeNo: "",
    erpIdentifier: "",
    erpDepartmentIdentifiers: [],
    cursor: "",
    pageSize: 0,
    credentialEnvelopeJson: new Uint8Array(0),
  };
}

export const ToolCallRequest: MessageFns<ToolCallRequest> = {
  encode(message: ToolCallRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.invocationId !== "") {
      writer.uint32(10).string(message.invocationId);
    }
    if (message.agentKey !== "") {
      writer.uint32(18).string(message.agentKey);
    }
    if (message.toolKey !== "") {
      writer.uint32(26).string(message.toolKey);
    }
    if (message.argsJson.length !== 0) {
      writer.uint32(34).bytes(message.argsJson);
    }
    if (message.organizationId !== "") {
      writer.uint32(42).string(message.organizationId);
    }
    if (message.userId !== "") {
      writer.uint32(50).string(message.userId);
    }
    if (message.conversationId !== "") {
      writer.uint32(58).string(message.conversationId);
    }
    if (message.deadlineMs !== 0) {
      writer.uint32(64).uint32(message.deadlineMs);
    }
    if (message.userEmail !== "") {
      writer.uint32(74).string(message.userEmail);
    }
    if (message.employeeNo !== "") {
      writer.uint32(82).string(message.employeeNo);
    }
    if (message.erpIdentifier !== "") {
      writer.uint32(90).string(message.erpIdentifier);
    }
    for (const v of message.erpDepartmentIdentifiers) {
      writer.uint32(98).string(v!);
    }
    if (message.cursor !== "") {
      writer.uint32(106).string(message.cursor);
    }
    if (message.pageSize !== 0) {
      writer.uint32(112).uint32(message.pageSize);
    }
    if (message.credentialEnvelopeJson.length !== 0) {
      writer.uint32(122).bytes(message.credentialEnvelopeJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.invocationId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.agentKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toolKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.argsJson = reader.bytes();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.organizationId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.conversationId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.deadlineMs = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.userEmail = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.employeeNo = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.erpIdentifier = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.erpDepartmentIdentifiers.push(reader.string());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.cursor = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 112) {
            break;
          }

          message.pageSize = reader.uint32();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.credentialEnvelopeJson = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallRequest {
    return {
      invocationId: isSet(object.invocationId)
        ? globalThis.String(object.invocationId)
        : isSet(object.invocation_id)
        ? globalThis.String(object.invocation_id)
        : "",
      agentKey: isSet(object.agentKey)
        ? globalThis.String(object.agentKey)
        : isSet(object.agent_key)
        ? globalThis.String(object.agent_key)
        : "",
      toolKey: isSet(object.toolKey)
        ? globalThis.String(object.toolKey)
        : isSet(object.tool_key)
        ? globalThis.String(object.tool_key)
        : "",
      argsJson: isSet(object.argsJson)
        ? bytesFromBase64(object.argsJson)
        : isSet(object.args_json)
        ? bytesFromBase64(object.args_json)
        : new Uint8Array(0),
      organizationId: isSet(object.organizationId)
        ? globalThis.String(object.organizationId)
        : isSet(object.organization_id)
        ? globalThis.String(object.organization_id)
        : "",
      userId: isSet(object.userId)
        ? globalThis.String(object.userId)
        : isSet(object.user_id)
        ? globalThis.String(object.user_id)
        : "",
      conversationId: isSet(object.conversationId)
        ? globalThis.String(object.conversationId)
        : isSet(object.conversation_id)
        ? globalThis.String(object.conversation_id)
        : "",
      deadlineMs: isSet(object.deadlineMs)
        ? globalThis.Number(object.deadlineMs)
        : isSet(object.deadline_ms)
        ? globalThis.Number(object.deadline_ms)
        : 0,
      userEmail: isSet(object.userEmail)
        ? globalThis.String(object.userEmail)
        : isSet(object.user_email)
        ? globalThis.String(object.user_email)
        : "",
      employeeNo: isSet(object.employeeNo)
        ? globalThis.String(object.employeeNo)
        : isSet(object.employee_no)
        ? globalThis.String(object.employee_no)
        : "",
      erpIdentifier: isSet(object.erpIdentifier)
        ? globalThis.String(object.erpIdentifier)
        : isSet(object.erp_identifier)
        ? globalThis.String(object.erp_identifier)
        : "",
      erpDepartmentIdentifiers: globalThis.Array.isArray(object?.erpDepartmentIdentifiers)
        ? object.erpDepartmentIdentifiers.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.erp_department_identifiers)
        ? object.erp_department_identifiers.map((e: any) => globalThis.String(e))
        : [],
      cursor: isSet(object.cursor) ? globalThis.String(object.cursor) : "",
      pageSize: isSet(object.pageSize)
        ? globalThis.Number(object.pageSize)
        : isSet(object.page_size)
        ? globalThis.Number(object.page_size)
        : 0,
      credentialEnvelopeJson: isSet(object.credentialEnvelopeJson)
        ? bytesFromBase64(object.credentialEnvelopeJson)
        : isSet(object.credential_envelope_json)
        ? bytesFromBase64(object.credential_envelope_json)
        : new Uint8Array(0),
    };
  },

  toJSON(message: ToolCallRequest): unknown {
    const obj: any = {};
    if (message.invocationId !== "") {
      obj.invocationId = message.invocationId;
    }
    if (message.agentKey !== "") {
      obj.agentKey = message.agentKey;
    }
    if (message.toolKey !== "") {
      obj.toolKey = message.toolKey;
    }
    if (message.argsJson.length !== 0) {
      obj.argsJson = base64FromBytes(message.argsJson);
    }
    if (message.organizationId !== "") {
      obj.organizationId = message.organizationId;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.conversationId !== "") {
      obj.conversationId = message.conversationId;
    }
    if (message.deadlineMs !== 0) {
      obj.deadlineMs = Math.round(message.deadlineMs);
    }
    if (message.userEmail !== "") {
      obj.userEmail = message.userEmail;
    }
    if (message.employeeNo !== "") {
      obj.employeeNo = message.employeeNo;
    }
    if (message.erpIdentifier !== "") {
      obj.erpIdentifier = message.erpIdentifier;
    }
    if (message.erpDepartmentIdentifiers?.length) {
      obj.erpDepartmentIdentifiers = message.erpDepartmentIdentifiers;
    }
    if (message.cursor !== "") {
      obj.cursor = message.cursor;
    }
    if (message.pageSize !== 0) {
      obj.pageSize = Math.round(message.pageSize);
    }
    if (message.credentialEnvelopeJson.length !== 0) {
      obj.credentialEnvelopeJson = base64FromBytes(message.credentialEnvelopeJson);
    }
    return obj;
  },

  create(base?: DeepPartial<ToolCallRequest>): ToolCallRequest {
    return ToolCallRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ToolCallRequest>): ToolCallRequest {
    const message = createBaseToolCallRequest();
    message.invocationId = object.invocationId ?? "";
    message.agentKey = object.agentKey ?? "";
    message.toolKey = object.toolKey ?? "";
    message.argsJson = object.argsJson ?? new Uint8Array(0);
    message.organizationId = object.organizationId ?? "";
    message.userId = object.userId ?? "";
    message.conversationId = object.conversationId ?? "";
    message.deadlineMs = object.deadlineMs ?? 0;
    message.userEmail = object.userEmail ?? "";
    message.employeeNo = object.employeeNo ?? "";
    message.erpIdentifier = object.erpIdentifier ?? "";
    message.erpDepartmentIdentifiers = object.erpDepartmentIdentifiers?.map((e) => e) || [];
    message.cursor = object.cursor ?? "";
    message.pageSize = object.pageSize ?? 0;
    message.credentialEnvelopeJson = object.credentialEnvelopeJson ?? new Uint8Array(0);
    return message;
  },
};

function createBaseHeartbeatAck(): HeartbeatAck {
  return { at: undefined };
}

export const HeartbeatAck: MessageFns<HeartbeatAck> = {
  encode(message: HeartbeatAck, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.at !== undefined) {
      Timestamp.encode(toTimestamp(message.at), writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartbeatAck {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartbeatAck();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.at = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeartbeatAck {
    return { at: isSet(object.at) ? fromJsonTimestamp(object.at) : undefined };
  },

  toJSON(message: HeartbeatAck): unknown {
    const obj: any = {};
    if (message.at !== undefined) {
      obj.at = message.at.toISOString();
    }
    return obj;
  },

  create(base?: DeepPartial<HeartbeatAck>): HeartbeatAck {
    return HeartbeatAck.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<HeartbeatAck>): HeartbeatAck {
    const message = createBaseHeartbeatAck();
    message.at = object.at ?? undefined;
    return message;
  },
};

function createBaseGoAway(): GoAway {
  return { reason: "" };
}

export const GoAway: MessageFns<GoAway> = {
  encode(message: GoAway, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reason !== "") {
      writer.uint32(10).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GoAway {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGoAway();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GoAway {
    return { reason: isSet(object.reason) ? globalThis.String(object.reason) : "" };
  },

  toJSON(message: GoAway): unknown {
    const obj: any = {};
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create(base?: DeepPartial<GoAway>): GoAway {
    return GoAway.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<GoAway>): GoAway {
    const message = createBaseGoAway();
    message.reason = object.reason ?? "";
    return message;
  },
};

export type ConnectorHubService = typeof ConnectorHubService;
export const ConnectorHubService = {
  connect: {
    path: "/vested.v1.ConnectorHub/Connect" as const,
    requestStream: true as const,
    responseStream: true as const,
    requestSerialize: (value: ConnectorMsg): Buffer => Buffer.from(ConnectorMsg.encode(value).finish()),
    requestDeserialize: (value: Buffer): ConnectorMsg => ConnectorMsg.decode(value),
    responseSerialize: (value: HubMsg): Buffer => Buffer.from(HubMsg.encode(value).finish()),
    responseDeserialize: (value: Buffer): HubMsg => HubMsg.decode(value),
  },
} as const;

export interface ConnectorHubServer extends UntypedServiceImplementation {
  connect: handleBidiStreamingCall<ConnectorMsg, HubMsg>;
}

export interface ConnectorHubClient extends Client {
  connect(): ClientDuplexStream<ConnectorMsg, HubMsg>;
  connect(options: Partial<CallOptions>): ClientDuplexStream<ConnectorMsg, HubMsg>;
  connect(metadata: Metadata, options?: Partial<CallOptions>): ClientDuplexStream<ConnectorMsg, HubMsg>;
}

export const ConnectorHubClient = makeGenericClientConstructor(
  ConnectorHubService,
  "vested.v1.ConnectorHub",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): ConnectorHubClient;
  service: typeof ConnectorHubService;
  serviceName: string;
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from((globalThis as any).Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return (globalThis as any).Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
